### ISSUE TITLE
tasklaunchrequest-transform - incorrect app type

### ISSUE THREAD

**Issue by nchandrappa** [spring-cloud-stream-app-starters/tasklaunchrequest-transform#2]
On importing apps from http://bit.ly/Avogadro-SR1-stream-applications-rabbit-maven, tasklaunchrequest-transform gets listed as **sink** however it should get listed as **processor**. Because of this following exception gets thrown on deploying the stream,

```
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: failed to resolve MavenResource: org.springframework.cloud.stream.app:tasklaunchrequest-transform-sink-rabbit:jar:1.1.1.RELEASE. Configured remote repository: REPO1_URL
```

**Comment by sabbyanandan** [comment]
This is addressed in Bacon.RELEASE -> http://bit.ly/Bacon-RELEASE-stream-applications-rabbit-maven
