### ISSUE TITLE
Transform needs to be able to set the application-name of the task via option

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud-stream-app-starters/tasklaunchrequest-transform#5]
Currently triggertask supports the ability to set application name of the task via its options.  This feature needs to be supported by the tasklaunchrequest-transform.

**Comment by sabbyanandan** [comment]
Isn't this a duplicate of spring-cloud-stream-app-starters/tasklaunchrequest-transform#4?

**Comment by cppwfs** [comment]
Duplicate of #4   Closing
